packages:
    - packages/*
    - packages/*/npm/*
    - tests/*
    - benchmarks/javascript
    - examples/javascript/*

autoInstallPeers: false
strictPeerDependencies: false

overrides:
    "@emnapi/core": 2.0.0-alpha.5
    "@emnapi/runtime": 2.0.0-alpha.5
    emnapi: 2.0.0-alpha.5

catalogs:
    test:
        vite: ^8
        vitest: ^5

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
    - "@napi-rs/*"
