name: Code Quality

on:
    pull_request:
    push:

jobs:
    lint:
        name: Lint
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install just
              uses: extractions/setup-just@v4

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: "1.97.0"
                  components: clippy
                  target: wasm32-wasip1-threads

            - name: Setup Node
              uses: alpheusci/setup-node@v1
              with:
                  auto-install: false

            - name: Install ls-lint
              run: brew install ls-lint

            - name: Install typos-cli
              run: brew install typos-cli

            - name: Prebuild
              run: |
                  just i
                  just create-npm-dirs
                  just i
                  just build

            - name: Run ls-lint
              run: just ls-lint

            - name: Run typos-cli
              run: just typos

            - name: Run linter
              run: just lint
