name: Test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    node:
        name: ${{ matrix.os.name }} / Rust ${{ matrix.rust.name }}
        runs-on: ${{ matrix.os.code }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - name: Linux
                      code: ubuntu-latest
                    - name: macOS
                      code: macos-latest
                    - name: Windows
                      code: windows-latest
                rust:
                    - name: "1.97.0"
                      code: "1.97.0"
                    - name: Stable
                      code: stable
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Install just
              uses: extractions/setup-just@v4

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v2
              with:
                  toolchain: ${{ matrix.rust.code }}

            - name: Setup Node
              uses: alpheusci/setup-node@v1

            - name: Prebuild
              run: just create-npm-dirs && just build

            - name: Run tests
              run: just test
